import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { Fat12Image } from './fat12'
import { decodeMsa } from './msa'
import { decodeStx } from './stx'

const here = dirname(fileURLToPath(import.meta.url))
const fixturesDir = join(here, '__fixtures__')

function loadStFixture(): Uint8Array {
	// Read as Buffer, copy into a fresh Uint8Array so we don't carry Buffer's
	// Node-specific prototype into the test (some assertions get confused).
	const buf = readFileSync(join(fixturesDir, 'sample.st'))
	return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength)
}

function loadMsaFixture(): Uint8Array {
	const buf = readFileSync(join(fixturesDir, 'sample.msa'))
	return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength)
}

function loadStxFixture(): Uint8Array {
	const buf = readFileSync(join(fixturesDir, 'sample.stx'))
	return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength)
}

/**
 * Integration tests for the disk-reading pipeline against a real 720 KB
 * Atari ST floppy image generated by GNU mtools (see scripts/gen-fixtures.mjs).
 *
 * Fixture layout:
 *   /HELLO.TXT          "Hello, Atari ST!\r\n"
 *   /READ.ME            "This is diskcheck's fixture image.\r\n"
 *   /SUB/INSIDE.TXT     "I live in a subdirectory.\r\n"
 */
describe('Fat12Image — integration with mtools-generated .st fixture', () => {
	it('parses the boot sector geometry of a 720KB DD floppy', () => {
		const img = new Fat12Image(loadStFixture())
		// Geometry read straight from the boot sector's BPB. mtools 4.0.49
		// produces a thinner FAT than the canonical ST format (3 sectors per
		// FAT, not 5), but the layout is still standard FAT12 — our code
		// trusts the BPB rather than hardcoding values.
		expect(img.geometry.bytesPerSector).toBe(512)
		expect(img.geometry.sectorsPerCluster).toBe(2)
		expect(img.geometry.numFats).toBe(2)
		expect(img.geometry.rootEntries).toBe(112)
		expect(img.geometry.totalSectors).toBe(1440)
		expect(img.geometry.sectorsPerFat).toBeGreaterThanOrEqual(3)
	})

	it('lists files recursively, descending into subdirectories', () => {
		const img = new Fat12Image(loadStFixture())
		const paths = img.listFiles().map(f => f.path).sort()
		expect(paths).toEqual(['/HELLO.TXT', '/READ.ME', '/SUB/INSIDE.TXT'])
	})

	it('reads HELLO.TXT and returns its contents verbatim', () => {
		const img = new Fat12Image(loadStFixture())
		const entry = img.findFile('/HELLO.TXT')?.entry
		expect(entry).toBeDefined()
		expect(entry!.size).toBe('Hello, Atari ST!\r\n'.length)

		const bytes = img.readFile(entry!)
		expect(Array.from(bytes)).toEqual(
			Array.from(Buffer.from('Hello, Atari ST!\r\n', 'latin1')),
		)
	})

	it('reads a nested file inside a subdirectory', () => {
		const img = new Fat12Image(loadStFixture())
		const entry = img.findFile('/SUB/INSIDE.TXT')?.entry
		expect(entry).toBeDefined()

		const bytes = img.readFile(entry!)
		expect(Buffer.from(bytes).toString('latin1')).toBe('I live in a subdirectory.\r\n')
	})
})

describe('Fat12Image via MSA decoder — same fixture, .msa form', () => {
	it('decodes the .msa fixture and produces identical files to the .st', () => {
		const stImage = new Fat12Image(loadStFixture())
		const msaImage = new Fat12Image(decodeMsa(loadMsaFixture()).raw)

		const stFiles = stImage.listFiles().map(f => f.path).sort()
		const msaFiles = msaImage.listFiles().map(f => f.path).sort()
		expect(msaFiles).toEqual(stFiles)

		for (const path of stFiles) {
			const stEntry = stImage.findFile(path)!.entry
			const msaEntry = msaImage.findFile(path)!.entry
			expect(msaEntry.size).toBe(stEntry.size)
			expect(msaImage.readFile(msaEntry)).toEqual(stImage.readFile(stEntry))
		}
	})
})

describe('Fat12Image via STX decoder — same fixture, .stx form', () => {
	it('decodes the .stx fixture and produces identical files to the .st', () => {
		const stImage = new Fat12Image(loadStFixture())
		const stxImage = new Fat12Image(decodeStx(loadStxFixture()).raw)

		const stFiles = stImage.listFiles().map(f => f.path).sort()
		const stxFiles = stxImage.listFiles().map(f => f.path).sort()
		expect(stxFiles).toEqual(stFiles)

		for (const path of stFiles) {
			const stEntry = stImage.findFile(path)!.entry
			const stxEntry = stxImage.findFile(path)!.entry
			expect(stxEntry.size).toBe(stEntry.size)
			expect(stxImage.readFile(stxEntry)).toEqual(stImage.readFile(stEntry))
		}
	})
})
