#!/usr/bin/env node
// Generates src/lib/charsets/atariST.ts from the Unicode Consortium's
// ATARIST.TXT mapping (downloaded to scripts/ATARIST.TXT).
//
// Usage:
//   curl -o scripts/ATARIST.TXT \
//     https://www.unicode.org/Public/MAPPINGS/VENDORS/MISC/ATARIST.TXT
//   node scripts/gen-atarist.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = dirname(here)
const sourcePath = join(root, 'scripts', 'ATARIST.TXT')
const outPath = join(root, 'src', 'lib', 'charsets', 'atariST.ts')

const raw = readFileSync(sourcePath, 'utf8')

const table = new Array(256)
const names = new Array(256)

for (const line of raw.split(/\r?\n/)) {
	if (!line || line.startsWith('#')) continue
	const m = line.match(/^0x([0-9A-Fa-f]{2})\s+0x([0-9A-Fa-f]+)\s+#\s*(.*)$/)
	if (!m) continue
	const byte = parseInt(m[1], 16)
	const codepoint = parseInt(m[2], 16)
	// Keep just the Unicode name (everything before the first tab in the comment).
	const name = m[3].split('\t')[0].trim().replace(/\s+$/, '')
	table[byte] = codepoint
	names[byte] = name
}

for (let i = 0; i < 256; i++) {
	if (table[i] === undefined) {
		throw new Error(`No mapping for byte 0x${i.toString(16).padStart(2, '0').toUpperCase()}`)
	}
}

const out = `// AUTO-GENERATED by scripts/gen-atarist.mjs — do not edit by hand.
// Source: https://www.unicode.org/Public/MAPPINGS/VENDORS/MISC/ATARIST.TXT
// Maps a single Atari ST byte (0x00–0xFF) to a Unicode codepoint.

export const ATARI_ST_TO_UNICODE: readonly number[] = Object.freeze([
${table.map((cp, i) => `\t0x${cp.toString(16).padStart(4, '0').toUpperCase()}, // 0x${i.toString(16).padStart(2, '0').toUpperCase()} ${names[i]}`).join('\n')}
])

// Convenience: a single string holding all 256 characters in codepoint order.
// Useful for eyeballing the table in tests.
export const ATARI_ST_SAMPLE = String.fromCodePoint(...ATARI_ST_TO_UNICODE)
`

writeFileSync(outPath, out)
console.log(`Wrote ${outPath} (${table.length} entries)`)
